export const WORKFLOW_CONSTANTS = {
  MAX_EXECUTION_STEPS: 100,
  DEFAULT_CANVAS_ZOOM: 1,
  MIN_ZOOM: 0.1,
  MAX_ZOOM: 2,
  NODE_DEFAULT_WIDTH: 180,
  NODE_DEFAULT_HEIGHT: 40,
  EDGE_VALIDATION_ENABLED: true,
  EXECUTION_STEP_DELAY_MS: 0,
  SERIALIZATION_FORMAT_VERSION: '1.0.0',
  VALID_NODE_TYPES: ['START', 'TRANSFORM', 'DECISION', 'SWITCH', 'END'] as const,
} as const
